version: '2.1'

services:
    mysql:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_DATABASE: sftpd
            MYSQL_ROOT_PASSWORD: root
        healthcheck:
            test:  mysql -uroot -proot -e 'SHOW TABLES' sftpd

    sftpd:
        image: maven:3-jdk-8-alpine
        working_dir: /usr/share/statflo
        command: mvn clean spring-boot:run
        ports:
            - "2222:2222"
        environment:
            - AWS_REGION=ca-central-1
            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID- }
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY- }

            - SPRING_PROFILES_ACTIVE=default,local
        volumes:
            - "./:/usr/share/statflo"
            - "./.volumes/m2:/root/.m2"
        depends_on:
            mysql:
                condition: service_healthy