logging:
  level:
    root: info

app:
  sftp:
    port: 2222 # Sftp server port
    base-folder: "/tmp/test-sftp"
    users: []
    aws:
      bucket-name: "{ssmParameter}/sftp/s3/bucket-name"
    hostkey-algorithm: "RSA"
    hostkey-private: "{ssmParameter}/sftp/sshd/hostkey-private"

server:
  port: 8090

spring:
#  localstack: ## TODO: figure out how to autowire in the localstack config? https://github.com/fabianoo/spring-localstack
#    enabled: true
  application:
    name: sftpDataExchange
  datasource:
    platform: h2
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "{ssmParameter}/sftp/database/jdbc-connection"
    username: "{ssmParameter}/sftp/database/username"
    password: "{ssmParameter}/sftp/database/password"
    tomcat:
      min-idle: 1
      max-idle: 2
      max-active: 15
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        cache:
          use_second_level_cache: false
  jackson:
    serialization:
      write_dates_as_timestamps: false

management:
  context-path: /manage
  security:
    enabled: false

security:
  basic:
    enabled: false
