version: 2
jobs:
  setup:
    -  make setup-circleci
  build:
    - checkout
    - run: make build
  push:
    - run: make push
  deploy:
    - run: make deploy ENVIRONMENT=prod

workflows:
    version: 2
    build_and_deploy:
      jobs:
        - setup
        - build:
            requires:
              - setup
        - push:
            requires:
              - build
        - deploy:
            requires:
              - push
            filters:
                branches:
                    only:
                      - circle
          